version: '2'

services:
    engine:
        build: ./docker/engine/
        dns:
            - 8.8.8.8
        volumes:
            - .:/home/docker:rw
            - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
        working_dir: /home/docker
        networks:
            - default
        dns_search:
            - engine

    db:
        image: postgres
        ports:
            - 3306
        environment:
            - POSTGRES_PASSWORD=dev
            - POSTGRES_USER=dev
            - POSTGRES_DB=dev
        volumes:
            - db:/var/lib/mysql:rw
        networks:
            - default
        dns_search:
            - db
    rabbitmq:
        image: rabbitmq:management
        ports:
            - 8080:15672
            - 5672:5672
        networks:
            - default
        dns_search: rabbitmq
volumes:
    db: {}

networks:
    default: {}
